server:
  port: 8081
  
spring:
  application:
    name: 'supplier'  jpa:    hibernate:      ddl-auto: update  datasource:    url: jdbc:mysql://localhost:3306/supplier    driver-class-name: com.mysql.jdbc.Driver    password:     username: root

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

